version: "3.2"
services:
  web:
    image: afreehling/express-ts
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      NODE_ENV: docker
    volumes:
      - .:/usr/src/app
